version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.55
    ports:
      - "16686:16686"  # Jaeger UI
      - "4318:4318"    # OTLP HTTP (default for OpenTelemetry Exporter)
      - "6831:6831/udp" # Jaeger agent UDP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - LOG_LEVEL=info
